<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UlasanPermohonanQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'id' => 1,
                'question' => 'Bagaimana pendapat saudara tentang kesesuaian persyaratan pelayanan dengan jenis pelayanannya?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 1,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak sesuai', 'Kurang sesuai', 'Sesuai', 'Sangat sesuai'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 2,
                'question' => 'Bagaimana pemahaman Saudara tentang kemudahan prosedur pelayanan di unit ini?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 2,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak mudah', 'Kurang mudah', 'Mudah', 'Sangat mudah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 3,
                'question' => 'Bagaimana pendapat Saudara tentang kecepatan waktu dalam memberikan pelayanan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 3,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak cepat', 'Kadang cepat', 'Cepat', 'Sangat cepat'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 4,
                'question' => 'Bagaimana pendapat Saudara tentang kewajaran biaya/tarif pengujian dalam pelayanan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 4,
                'note' => 'Pilih salah satu opsi yang sesuai',
                'rating_labels' => json_encode(['Harga tidak sesuai dengan apa yg tercantum dalam website', '', '', 'Harga sesuai dengan apa yg tercantum dalam website'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 5,
                'question' => 'Bagaimana pendapat Saudara tentang kesesuaian produk pelayanan antara yang tercantum dalam standar pelayanan dengan hasil yang diberikan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 5,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak sesuai', 'Kurang sesuai', 'Sesuai', 'Sangat sesuai'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 6,
                'question' => 'Bagaimana pendapat Saudara tentang kompetensi/kemampuan petugas dalam pelayanan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 6,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak kompeten', 'Kurang kompeten', 'Kompeten', 'Sangat kompeten'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 7,
                'question' => 'Bagaimana pendapat Saudara perilaku petugas dalam pelayanan terkait kesopanan & keramahan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 7,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak sopan & ramah', 'Kurang sopan & ramah', 'Sopan & ramah', 'Sangat sopan & ramah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 8,
                'question' => 'Bagaimana pendapat Saudara tentang kualitas sarana dan prasarana?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 8,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Buruk', 'Cukup', 'Baik', 'Sangat Baik'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 9,
                'question' => 'Bagaimana pendapat Saudara tentang penanganan pengaduan pengguna layanan?',
                'type' => 'rating',
                'category' => 'ikm',
                'is_active' => 1,
                'sort_order' => 9,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Tidak ada', 'Ada tetapi tidak berfungsi', 'Berfungsi kurang maksimal', 'Dikelola dengan baik'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 10,
                'question' => 'Apakah saudara pernah mendapati praktik diskriminatif dalam pemberian layanan?',
                'type' => 'rating',
                'category' => 'ikk',
                'is_active' => 1,
                'sort_order' => 10,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Sering', 'Beberapa kali', 'Sekali', 'Tidak pernah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 11,
                'question' => 'Apakah saudara pernah mendapati praktik kecurangan dalam pemberian layanan?',
                'type' => 'rating',
                'category' => 'ikk',
                'is_active' => 1,
                'sort_order' => 11,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Sering', 'Beberapa kali', 'Sekali', 'Tidak pernah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 12,
                'question' => 'Apakah saudara pernah mendapati petugas pelayanan menerima imbalan?',
                'type' => 'rating',
                'category' => 'ikk',
                'is_active' => 1,
                'sort_order' => 12,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Sering', 'Beberapa kali', 'Sekali', 'Tidak pernah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 13,
                'question' => 'Apakah saudara pernah mendapati praktik pungutan liar dalam pemberian layanan?',
                'type' => 'rating',
                'category' => 'ikk',
                'is_active' => 1,
                'sort_order' => 13,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Sering', 'Beberapa kali', 'Sekali', 'Tidak pernah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
            [
                'id' => 14,
                'question' => 'Apakah saudara pernah mendapati praktik percaloan/perantara tidak resmi dalam pemberian layanan?',
                'type' => 'rating',
                'category' => 'ikk',
                'is_active' => 1,
                'sort_order' => 14,
                'note' => 'Skala 1-4',
                'rating_labels' => json_encode(['Sering', 'Beberapa kali', 'Sekali', 'Tidak pernah'], JSON_UNESCAPED_UNICODE),
                'created_at' => '2026-03-06 01:27:19',
                'updated_at' => '2026-03-06 01:27:19',
            ],
        ];

        DB::table('ulasan_permohonan_questions')->upsert(
            $questions,
            ['id'],
            ['question', 'type', 'category', 'is_active', 'sort_order', 'note', 'rating_labels', 'created_at', 'updated_at']
        );
    }
}
